version: 1.1.{build}
image: Visual Studio 2022
configuration: Debug
before_build:
  - nuget restore
build:
  project: .\SerialPortLib.sln
  verbosity: minimal
test:
  assemblies:
    only:
      - SerialPortLib.Tests/bin/Debug/SerialPortLib.Tests.dll
after_test:
  - ps: .\SerialPortLib\nuget_pack.ps1
artifacts:
  - path: '*.nupkg'
    name: SerialPortLib nupkg
    type: NuGetPackage
deploy:
  - provider: NuGet
    api_key:
      secure: ER771ujBnbfc/o+8QyM3XZInr0JyFfv3GIdDyQZfZtNUuCCkDn4cFEc1ZJGCYkpt
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true
